### ISSUE TITLE
Document Issues

### ISSUE THREAD

**Issue by HerbertHe** [Next2D/next2d.app#8]
https://github.com/Next2D/next2d.app/blob/2bd160c8e02ddb8bf4a165a593d19a110ecea6d5/language/en/framework-api.json#L35

`contractor of the specified class` means `constructor of the specified class`? 

And, could you please explain the meaning of the following sentence?

https://github.com/Next2D/next2d.app/blob/2bd160c8e02ddb8bf4a165a593d19a110ecea6d5/language/en/framework-api.json#L18

**Comment by ienaga** [comment]
@HerbertHe 

Thanks issues.

> contractor of the specified class means constructor of the specified class?

Yes, I am interested. That is correct.
The mechanism is to set variables in the constructor of the class specified in json and call the execute function.

https://github.com/Next2D/framework/blob/784d63af8640d5d1c367005b03dbf43f0a6b2156/src/Application.js#L514

> And, could you please explain the meaning of the following sentence?

config.json can set fixed variables.
For example, if you change the URL of the API used in the local environment and the URL of the API used in production, you can manage different URLs by separating them with "local" and "prd".
You can use npm build --env="***" to write out the URLs for each environment.

Fixed variables that you want to use in all environments can be set to all to use the same fixed variables in all environments.

https://github.com/Next2D/framework-template/blob/main/template/src/config/config.json


The description was strange, so I made some changes.
https://github.com/Next2D/next2d.app/commit/2d281cf8f22f094ed1f472907ed4eef737399b9d

**Comment by HerbertHe** [comment]
なのほど!
